const API=String(window.LAPIN_CONFIG?.API_URL||'').replace(/\/$/,'');const PASSWORD='1234';const money=n=>Number(n||0).toLocaleString('fr-FR')+' FCFA';let products=[],moves=[];
async function api(path,options={}){if(!API)throw new Error('API_URL non configurée dans config.js');const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erreur serveur');return d}
async function refresh(){products=await api('/api/products');moves=await api('/api/stock/movements')}
function login(){if(document.getElementById('password').value!==PASSWORD){document.getElementById('loginError').textContent='Mot de passe incorrect.';return}localStorage.setItem('lapinAdmin','1');document.getElementById('login').hidden=true;document.getElementById('app').hidden=false;init()}
document.getElementById('loginBtn').onclick=login;document.getElementById('password').onkeydown=e=>{if(e.key==='Enter')login()};document.getElementById('logout').onclick=()=>{localStorage.removeItem('lapinAdmin');location.reload()};
function showSection(id){document.querySelectorAll('.section').forEach(s=>s.hidden=s.id!==id);document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.section===id));document.getElementById('pageTitle').textContent={dashboard:'Tableau de bord',products:'Préparations',movements:'Entrées / Sorties',history:'Historique'}[id];if(id==='dashboard')renderDashboard();if(id==='products')renderProducts();if(id==='movements')fillMoveProducts();if(id==='history')renderHistory()}window.showSection=showSection;document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>showSection(n.dataset.section));
function tableStock(ps){if(!ps.length)return '<div class="empty">Aucune préparation.</div>';return '<table class="table"><tr><th>Préparation</th><th>Catégorie</th><th>Stock</th><th>Prix</th><th>État</th></tr>'+ps.map(p=>`<tr><td>${p.name}</td><td>${p.category}</td><td><b>${p.stock}</b></td><td>${money(p.price)}</td><td><span class="badge ${p.stock===0?'out':p.stock<=3?'low':'ok'}">${p.stock===0?'RUPTURE':p.stock<=3?'STOCK FAIBLE':'DISPONIBLE'}</span></td></tr>`).join('')+'</table>'}
async function renderDashboard(){try{const d=await api('/api/dashboard');document.getElementById('totalStock').textContent=d.totalStock;document.getElementById('totalIn').textContent=d.totalIn;document.getElementById('totalOut').textContent=d.totalOut;document.getElementById('revenue').textContent=money(d.revenue);document.getElementById('stockTable').innerHTML=tableStock(products)}catch(e){alert(e.message)}}
function renderProducts(){document.getElementById('productsTable').innerHTML=products.length?'<table class="table"><tr><th>Produit</th><th>Catégorie</th><th>Poids</th><th>Prix</th><th>Stock</th><th>Action</th></tr>'+products.map(p=>`<tr><td><b>${p.name}</b><br><small>${p.code}</small></td><td>${p.category}</td><td>${p.weight||'—'}</td><td>${money(p.price)}</td><td>${p.stock}</td><td class="product-actions"><button onclick="editProduct(${p.id})">Modifier</button><button onclick="deleteProduct(${p.id})">Supprimer</button></td></tr>`).join('')+'</table>':'<div class="empty">Aucune préparation.</div>'}
window.editProduct=async id=>{const p=products.find(x=>Number(x.id)===Number(id));if(!p)return;const name=prompt('Nom',p.name),price=prompt('Prix FCFA',p.price),weight=prompt('Poids',p.weight||'');if(!name||price===null)return;try{await api('/api/products/'+id,{method:'PUT',body:JSON.stringify({name,price:Number(price),weight,category:p.category,description:p.description||'',image:p.image||''})});await refresh();renderProducts();renderDashboard()}catch(e){alert(e.message)}};
window.deleteProduct=async id=>{if(!confirm('Supprimer cette préparation du catalogue ?'))return;try{await api('/api/products/'+id,{method:'DELETE'});await refresh();renderProducts();renderDashboard();fillMoveProducts()}catch(e){alert(e.message)}};
document.getElementById('addProduct').onclick=async()=>{const name=prompt('Nom de la préparation');if(!name)return;const price=Number(prompt('Prix en FCFA','8000')||0),stock=Number(prompt('Stock initial','0')||0),weight=prompt('Poids','1 kg')||'',category=prompt('Catégorie : entier, portion ou grille','entier')||'entier',image=prompt('URL de la photo','')||'';try{await api('/api/products',{method:'POST',body:JSON.stringify({code:'LP-'+Date.now().toString().slice(-6),name,category,weight,price,stock,image})});await refresh();renderProducts();renderDashboard();fillMoveProducts()}catch(e){alert(e.message)}};
function fillMoveProducts(){document.getElementById('moveProduct').innerHTML=products.map(p=>`<option value="${p.id}">${p.name} — stock ${p.stock}</option>`).join('');const p=products[0];if(p)document.getElementById('movePrice').value=p.price}document.getElementById('moveProduct').onchange=e=>{const p=products.find(x=>Number(x.id)===Number(e.target.value));if(p)document.getElementById('movePrice').value=p.price};
document.getElementById('saveMove').onclick=async()=>{const type=document.getElementById('moveType').value,productId=Number(document.getElementById('moveProduct').value),quantity=Number(document.getElementById('moveQty').value),unitPrice=Number(document.getElementById('movePrice').value),reason=document.getElementById('moveNote').value.trim(),msg=document.getElementById('moveMsg');try{await api('/api/stock/movement',{method:'POST',body:JSON.stringify({productId,type,quantity,unitPrice,reason})});msg.className='success';msg.textContent=type==='in'?'Entrée enregistrée.':'Sortie enregistrée.';await refresh();renderDashboard();fillMoveProducts();renderHistory()}catch(e){msg.className='error';msg.textContent=e.message}};
function renderHistory(){document.getElementById('historyTable').innerHTML=moves.length?'<table class="table"><tr><th>Date</th><th>Type</th><th>Préparation</th><th>Qté</th><th>Prix</th><th>Note</th></tr>'+moves.map(m=>`<tr><td>${new Date(m.created_at).toLocaleString('fr-FR')}</td><td><span class="badge ${m.type==='in'?'ok':'out'}">${m.type==='in'?'ENTRÉE':'SORTIE'}</span></td><td>${m.name}</td><td>${m.quantity}</td><td>${money(m.unit_price)}</td><td>${m.reason||'—'}</td></tr>`).join('')+'</table>':'<div class="empty">Aucun mouvement enregistré.</div>'}document.getElementById('clearHistory').onclick=()=>alert('L’historique est conservé dans la base de données pour la traçabilité.');
async function init(){document.getElementById('today').textContent=new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});try{await refresh();renderProducts();fillMoveProducts();await renderDashboard()}catch(e){alert(e.message)}}if(localStorage.getItem('lapinAdmin')==='1'){document.getElementById('login').hidden=true;document.getElementById('app').hidden=false;init()}
