const PHONE='2250700000000';
const API=String(window.LAPIN_CONFIG?.API_URL||'').replace(/\/$/,'');
const money=n=>Number(n||0).toLocaleString('fr-FR')+' FCFA';
const defaults=[{id:'LP-001',name:'Lapin entier préparé',category:'entier',weight:'1,2 kg',price:8000,stock:8,image:'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=1000&q=85'},{id:'LP-002',name:'Lapin entier préparé premium',category:'entier',weight:'1,5 kg',price:10000,stock:5,image:'https://images.unsplash.com/photo-1535241749838-299277b6305f?auto=format&fit=crop&w=1000&q=85'},{id:'LP-003',name:'Portion de lapin',category:'portion',weight:'500 g',price:4500,stock:12,image:'https://images.unsplash.com/photo-1525253086316-d0c936c814f8?auto=format&fit=crop&w=1000&q=85'},{id:'LP-004',name:'Lapin grillé',category:'grille',weight:'1 portion',price:7000,stock:6,image:'https://images.unsplash.com/photo-1591561582301-7ce6588cc286?auto=format&fit=crop&w=1000&q=85'}];
let products=[];
async function loadProducts(){
 const status=document.getElementById('apiStatus');
 if(API){try{const r=await fetch(API+'/api/products',{cache:'no-store'});if(!r.ok)throw new Error();products=await r.json();status.textContent='Stock en temps réel';status.className='muted online';return;}catch(e){status.textContent='API indisponible — catalogue local affiché';}}
 products=defaults;render();
}
function render(){const grid=document.getElementById('grid');if(!grid)return;const q=(document.getElementById('search')?.value||'').toLowerCase();const cat=document.getElementById('category')?.value||'all';const list=products.filter(p=>Number(p.stock)>0&&((p.name+' '+(p.category||'')).toLowerCase().includes(q))&&(cat==='all'||p.category===cat));document.getElementById('empty').hidden=list.length>0;grid.innerHTML=list.map(p=>`<article class="card"><img src="${p.image||''}" alt="${p.name}"><div class="card-body"><span class="tag">${p.category==='grille'?'GRILLÉ':p.category==='portion'?'PORTION':'ENTIER'}</span><h3>${p.name}</h3><p>Poids : ${p.weight||'—'}<br>Disponible : ${p.stock}</p><div class="price">${money(p.price)}</div><a class="btn whatsapp" target="_blank" rel="noopener" href="https://wa.me/${PHONE}?text=${encodeURIComponent('Bonjour, je souhaite commander : '+p.name+' ('+(p.code||p.id)+') au prix de '+money(p.price)+'. Quantité souhaitée : 1. Est-il disponible ?')}">💬 Commander sur WhatsApp</a></div></article>`).join('')}
document.getElementById('search')?.addEventListener('input',render);document.getElementById('category')?.addEventListener('change',render);document.getElementById('contactWa')?.setAttribute('href','https://wa.me/'+PHONE+'?text='+encodeURIComponent('Bonjour, je souhaite avoir des informations sur vos lapins préparés.'));document.getElementById('year').textContent=new Date().getFullYear();loadProducts();
